swagger: '2.0'
info:
  description: Server API Documentation
  version: '1.0'
  title: Server API
host: localhost:8089
basePath: /
tags:
  - name: server-controller
    description: Server Controller
paths:
  /addServer:
    post:
      tags:
        - server-controller
      summary: Add a Server
      operationId: addServer
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: server
          description: Server object to add
          required: true
          schema:
            $ref: '#/definitions/Server'
      responses:
        '201':
          description: Server added successfully
          schema:
            $ref: '#/definitions/Server'
  /getServers:
    get:
      tags:
        - server-controller
      summary: Get All Servers
      operationId: getAllServers
      produces:
        - application/json
      responses:
        '200':
          description: List of all servers
          schema:
            type: array
            items:
              $ref: '#/definitions/Server'
  /getServerById/{id}:
    get:
      tags:
        - server-controller
      summary: Get a Server by ID
      operationId: getServerById
      produces:
        - application/json
      parameters:
        - name: id
          in: path
          description: ID of the server to retrieve
          required: true
          type: integer
      responses:
        '200':
          description: Server retrieved successfully
          schema:
            $ref: '#/definitions/Server'
        '404':
          description: Server not found
  /getServerByName:
    get:
      tags:
        - server-controller
      summary: Get a Server by Name
      operationId: getServerByName
      produces:
        - application/json
      parameters:
        - name: name
          in: query
          description: Name of the server to retrieve
          required: true
          type: string
      responses:
        '200':
          description: Server retrieved successfully
          schema:
            $ref: '#/definitions/Server'
        '404':
          description: Server not found
  /deleteServerById/{id}:
    delete:
      tags:
        - server-controller
      summary: Delete a Server by ID
      operationId: deleteServerById
      produces:
        - application/json
      parameters:
        - name: id
          in: path
          description: ID of the server to delete
          required: true
          type: integer
      responses:
        '200':
          description: Server deleted successfully
        '404':
          description: Server not found
definitions:
  Server:
    type: object
    required:
      - id
      - name
      - language
      - framework
    properties:
      id:
        type: integer
      name:
        type: string
      language:
        type: string
      framework:
        type: string
